[mypy]
python_version = 3.14
plugins = pydantic.mypy
strict = True
follow_imports = skip
ignore_missing_imports = True
show_error_codes = True

[mypy-polars.*]
ignore_missing_imports = True

[mypy-aiosqlite.*]
ignore_missing_imports = True

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-polars_ta.*]
ignore_missing_imports = True

[mypy-websockets.*]
ignore_missing_imports = True
