"""Canonical hunt data paths — extends hunt_watch.paths with lake layout."""

from __future__ import annotations

from pathlib import Path

from hunt_watch import paths as _legacy

# Re-export all legacy paths
ROOT = _legacy.ROOT
DATA = _legacy.DATA
SNAPSHOTS = _legacy.SNAPSHOTS
WATCHLIST = _legacy.WATCHLIST
SIGNAL_STATE = _legacy.SIGNAL_STATE
TELEGRAM_COOLDOWN = _legacy.TELEGRAM_COOLDOWN
TICK_JSONL = _legacy.TICK_JSONL
WATCH_LOG = _legacy.WATCH_LOG
IGNITION_STATE = _legacy.IGNITION_STATE
PUMP_HISTORY = _legacy.PUMP_HISTORY
EWMA_THRESHOLDS = _legacy.EWMA_THRESHOLDS
ADAPTIVE_THRESHOLDS = _legacy.ADAPTIVE_THRESHOLDS
HUNT_CALIBRATION = _legacy.HUNT_CALIBRATION
SESSION_DIR = _legacy.SESSION_DIR
SIGNAL_EVENTS = _legacy.SIGNAL_EVENTS
PREP_SHADOW_STATE = _legacy.PREP_SHADOW_STATE
PREP_SHADOW_EVENTS = _legacy.PREP_SHADOW_EVENTS
MARKET_REGIME = _legacy.MARKET_REGIME
SIGNAL_HISTORY = _legacy.SIGNAL_HISTORY
BACKTEST_OUTCOMES = _legacy.BACKTEST_OUTCOMES
BACKTEST_OUTCOMES_ENRICHED = _legacy.BACKTEST_OUTCOMES_ENRICHED
GATE_EDGE_OUTCOMES = _legacy.GATE_EDGE_OUTCOMES
INTEL_DOSSIER_MD = _legacy.INTEL_DOSSIER_MD
INTEL_DOSSIER_JSON = _legacy.INTEL_DOSSIER_JSON
INTEL_REPORT = _legacy.INTEL_REPORT
DEEP_WATCH_GLOB = _legacy.DEEP_WATCH_GLOB
DUMP_HUNT_ALERT_STATE = _legacy.DUMP_HUNT_ALERT_STATE

# Data lake (rewrite)
LAKE = DATA / "lake"
LAKE_DB = LAKE / "hunt_lake.sqlite"
LAKE_PARQUET = LAKE / "parquet"
UNIFIED_LABELS = DATA / "unified_labels.jsonl"
