"""Compat shim — canonical: ``runtime.state`` + ``domain.config`` (P11)."""
from __future__ import annotations

from hunt_core.domain.config import (
    COOLDOWN_MINUTES,
    IGNITION_MIN_PCT,
    IGNITION_MIN_QVOL_USD,
    IGNITION_MIN_VOL_DELTA_USD,
    IGNITION_TELEGRAM_ENABLED,
    IGNITION_TTL_S,
    IGNITION_WINDOW_S,
    SCAN_INTERVAL_S,
    SQUEEZE_BB_PCTILE_MAX,
    SQUEEZE_COOLDOWN_MINUTES,
    SQUEEZE_DONCHIAN_MAX_PCT,
    SQUEEZE_MIN_VOL_24H_M,
    SYMBOL_TICK_TIMEOUT_S,
    TICK_ROTATE_INTERVAL_S,
    TICK_ROTATE_MIN_BYTES,
)
from hunt_core.runtime.state import (
    LOG,
    OUT_PATH,
    SNIPER_CONFIG,
    STATE_PATH,
    STOP,
    SYMBOL_WATCH_MODES,
    SymbolSession,
    SymbolStateStore,
    WatchMode,
    current_symbol_state,
    load_session,
    merge_hunt_extremes,
    new_session_state,
    request_stop,
    save_session,
    set_symbol_state,
)

__all__ = [
    "COOLDOWN_MINUTES",
    "IGNITION_MIN_PCT",
    "IGNITION_MIN_QVOL_USD",
    "IGNITION_MIN_VOL_DELTA_USD",
    "IGNITION_TELEGRAM_ENABLED",
    "IGNITION_TTL_S",
    "IGNITION_WINDOW_S",
    "LOG",
    "OUT_PATH",
    "SCAN_INTERVAL_S",
    "SNIPER_CONFIG",
    "SQUEEZE_BB_PCTILE_MAX",
    "SQUEEZE_COOLDOWN_MINUTES",
    "SQUEEZE_DONCHIAN_MAX_PCT",
    "SQUEEZE_MIN_VOL_24H_M",
    "STATE_PATH",
    "STOP",
    "SYMBOL_TICK_TIMEOUT_S",
    "SYMBOL_WATCH_MODES",
    "SymbolSession",
    "SymbolStateStore",
    "TICK_ROTATE_INTERVAL_S",
    "TICK_ROTATE_MIN_BYTES",
    "WatchMode",
    "current_symbol_state",
    "load_session",
    "merge_hunt_extremes",
    "new_session_state",
    "request_stop",
    "save_session",
    "set_symbol_state",
]
