"""Deprecated shim — use hunt_core.deep.signal."""
from hunt_core.deep.signal import (  # noqa: F401
    LiquidityScenario,
    LiquidityScenarioPack,
    OrderFlowSynthesis,
    PocLevelScenario,
    PocLevelScenarioPack,
    apply_liquidity_to_mtf_scores,
    btc_market_context,
    build_liquidity_scenarios,
    build_poc_level_scenarios,
    fmt_flow_qty,
    format_liquidity_scenarios_telegram,
    format_order_flow_block,
    format_poc_level_scenarios_telegram,
    is_deep_analysis_context,
    resolve_trade_direction,
    synthesize_order_flow,
)

__all__ = [
    "LiquidityScenario",
    "LiquidityScenarioPack",
    "OrderFlowSynthesis",
    "PocLevelScenario",
    "PocLevelScenarioPack",
    "apply_liquidity_to_mtf_scores",
    "btc_market_context",
    "build_liquidity_scenarios",
    "build_poc_level_scenarios",
    "fmt_flow_qty",
    "format_liquidity_scenarios_telegram",
    "format_order_flow_block",
    "format_poc_level_scenarios_telegram",
    "is_deep_analysis_context",
    "resolve_trade_direction",
    "synthesize_order_flow",
]
